### ISSUE TITLE
Convert "vars" to "defaults".

### ISSUE THREAD

**Issue by dale-c-anderson** [AcroMedia/ansible-role-wkhtmltopdf#2]
Instead of wiring vars per OS, we need to let the role define defaults and let the playbook override them.

So that if a playbook pins a specific version, the role doesn't overwrite it, regardless if the pinned version is out of date or not.

OS-Dependent defaults can be accomplished thusly: 

`defaults/main.yml`
```yaml
my_role_variable_RedHat: "redhat specific default"
my_role_variable_Debian: "debian specific default"
my_role_variable: "{{ lookup('vars', 'my_role_variable_' + ansible_os_family) }}"
```

**Comment by dale-c-anderson** [comment]
Or if that ^^ doesn't work (i remember fighting with that style of variable definition a while back), this should: 
```yaml
some_variable_os:
  Debian: foo
  Redhat: bar

some_variable: "{{ some_variable_os[ansible_os_family] }}"
```
